const qs=(s,r=document)=>r.querySelector(s), qsa=(s,r=document)=>[...r.querySelectorAll(s)];
const stories=[
['Тихий Дэн','мистика','8 ч 47 мин','9.7',['Аудио','AI-фильм','Книга']],['Ночное такси','триллер','6 ч 12 мин','9.4',['Аудио','Видео']],['Сириус 6Б','фантастика','11 ч 03 мин','9.2',['Аудио','Игра']],['Ёжлесово','мистика','7 ч 40 мин','9.5',['Аудио','Книга']],['Курьер','триллер','5 ч 54 мин','9.0',['Аудио']],['Квартира 101','хоррор','9 ч 18 мин','9.3',['Аудио','Видео']],['Вода среди нас','мистика','10 ч 21 мин','8.9',['Аудио']],['Тёмное зло','хоррор','8 ч 05 мин','9.1',['Аудио','Книга']],['Бездна вечности','фантастика','12 ч 48 мин','9.6',['Аудио','Видео']],['Больница 286','хоррор','7 ч 26 мин','9.4',['Аудио']]
];
function card(s,i){return `<article class="story-card" data-title="${s[0].toLowerCase()}" data-genre="${s[1]}"><a href="work.html" aria-label="Открыть произведение ${s[0]}"><div class="poster" data-title="${s[0]}" style="--poster-accent:${i%2?'rgba(66,199,255,.6)':'rgba(255,77,40,.75)'}"></div></a><button class="icon-btn quickplay" aria-label="Быстро воспроизвести ${s[0]}" data-play="${s[0]}">▶</button><div class="story-body"><div class="story-title">${s[0]}</div><div class="meta-row"><span>${s[1]} · ${s[2]}</span><span>★ ${s[3]}</span></div><div class="formats">${s[4].map(x=>`<span class="format">${x}</span>`).join('')}</div></div></article>`}
function renderStories(){qsa('[data-story-grid]').forEach(g=>g.innerHTML=stories.map(card).join(''))}
renderStories();
const menu=qs('[data-menu]'), navlinks=qs('.navlinks'); if(menu)menu.onclick=()=>{const open=navlinks.style.display==='flex';navlinks.style.display=open?'none':'flex';if(!open){Object.assign(navlinks.style,{position:'absolute',top:'62px',left:'10px',right:'10px',padding:'16px',background:'#101319',border:'1px solid rgba(255,255,255,.1)',borderRadius:'16px',flexDirection:'column',alignItems:'stretch'})}menu.setAttribute('aria-expanded',String(!open))};
const toast=(t)=>{let el=qs('.toast');if(!el){el=document.createElement('div');el.className='toast';document.body.append(el)}el.textContent=t;el.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>el.classList.remove('show'),1800)};
let playing=false; qsa('[data-play], [data-main-play]').forEach(b=>b.onclick=()=>{playing=!playing;qsa('[data-main-play]').forEach(x=>x.textContent=playing?'❚❚':'▶');toast(playing?'Воспроизведение запущено':'Пауза')});
const saved=Number(localStorage.getItem('ozon671-progress')||37);qsa('.progress i,.dock-progress i').forEach(i=>i.style.width=saved+'%');
setInterval(()=>{if(playing){let p=Number(localStorage.getItem('ozon671-progress')||saved);p=Math.min(99,p+.05);localStorage.setItem('ozon671-progress',p);qsa('.progress i,.dock-progress i').forEach(i=>i.style.width=p+'%')}},1500);
qsa('[data-speed]').forEach(b=>b.onclick=()=>{let v=Number(b.dataset.speed||1);v=v>=2?.5:v+.25;b.dataset.speed=v;b.textContent=v+'×';toast('Скорость '+v+'×')});
const search=qs('[data-search]'); if(search) search.addEventListener('input',e=>{const v=e.target.value.toLowerCase().trim();qsa('.story-card').forEach(c=>c.hidden=v&&!c.dataset.title.includes(v))});
const catSearch=qs('[data-catalog-search]'), genre=qs('[data-genre]');function filterCatalog(){let v=(catSearch?.value||'').toLowerCase(),g=genre?.value||'';qsa('[data-story-grid] .story-card').forEach(c=>c.hidden=!!((v&&!c.dataset.title.includes(v))||(g&&c.dataset.genre!==g)))};catSearch?.addEventListener('input',filterCatalog);genre?.addEventListener('change',filterCatalog);
qsa('[data-view]').forEach(b=>b.onclick=()=>{const g=qs('[data-story-grid]');g.classList.toggle('catalog-list',b.dataset.view==='list');toast(b.dataset.view==='list'?'Режим: список':'Режим: сетка')});
qsa('.node').forEach(n=>n.onclick=()=>{qsa('.node').forEach(x=>x.classList.remove('active'));n.classList.add('active');const title=qs('[data-lore-title]'),text=qs('[data-lore-text]');if(title)title.textContent=n.dataset.title;if(text)text.textContent=n.dataset.text});
let cart=JSON.parse(localStorage.getItem('ozon671-cart')||'[]');function saveCart(){localStorage.setItem('ozon671-cart',JSON.stringify(cart));renderCart()}function renderCart(){const list=qs('[data-cart-list]'),count=qs('[data-cart-count]');if(count)count.textContent=cart.reduce((a,x)=>a+x.qty,0);if(!list)return;list.innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><div class="product-image">${x.name.slice(0,1)}</div><div><strong>${x.name}</strong><small class="muted">Количество: ${x.qty}</small></div><button class="icon-btn" data-remove="${i}" aria-label="Удалить">×</button></div>`).join(''):'<p class="muted">Корзина пока пуста.</p>';qsa('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);saveCart()})}renderCart();
qsa('[data-add-cart]').forEach(b=>b.onclick=()=>{const name=b.dataset.addCart;const item=cart.find(x=>x.name===name);item?item.qty++:cart.push({name,qty:1});saveCart();toast('Добавлено в корзину')});
const drawer=qs('[data-cart]');qsa('[data-cart-open]').forEach(b=>b.onclick=()=>drawer?.classList.add('open'));qs('[data-cart-close]')?.addEventListener('click',()=>drawer.classList.remove('open'));
qs('[data-checkout]')?.addEventListener('click',()=>toast('Демо-checkout: списание не производится'));
qs('[data-theme]')?.addEventListener('click',()=>toast('В прототипе доступна тёмная кинематографичная тема'));
